### ISSUE TITLE
[bug] y-direction zoom-in/out not working with a physical mouse wheel

### ISSUE THREAD

**Issue by ybillchen** [kgozman6159/lvd-interactive#1]
Currently, the y-direction zoom-in/out feature is triggered by `mouse wheel` + `shift`. However, `mouse wheel` + `shift` sometimes conflicts the horizontal scrolling function and does not zoom-in/out the plot properly. This bug happens when using a physical mouse.

Bill

**Comment by kgozman6159** [comment]
Thanks for catching this! This is a problem specifically on Macs (as you point out, that OS interprets shift+scroll as horizontal scrolling). Since there's no way for Mac users to change that setting, I've changed the y-axis scroll to be done with the `control` button instead of the `shift` button.
